import { LocalFoodEntry } from '../types';

export const RAW_COOKED_RATIOS: Record<string, number> = {
  rice: 2.7,
  dal: 3.0,
  lentil: 3.0,
  pasta: 2.8,
  chole: 2.6,
  chickpea: 2.6,
  chana: 2.6,
  oat: 5.8,
};

export const FOOD_DATABASE: LocalFoodEntry[] = [
  // Rice (raw / uncooked)
  {
    name: 'Rice (raw)',
    aliases: ['raw rice', 'uncooked rice', 'dry rice', 'rice raw'],
    caloriesPer100g: 350,
    proteinPer100g: 7,
    carbsPer100g: 78,
    fatPer100g: 0.6,
    defaultPortionGrams: 180,
    defaultPortionUnit: 'bowl',
  },
  // Rice
  {
    name: 'Rice',
    aliases: ['rice', 'chawal', 'cooked rice', 'steamed rice', 'plain rice', 'white rice'],
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28,
    fatPer100g: 0.3,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Dal (raw / uncooked)
  {
    name: 'Lentils (raw)',
    aliases: ['raw dal', 'uncooked dal', 'dry dal', 'raw lentils', 'uncooked lentils', 'dry lentils'],
    caloriesPer100g: 350,
    proteinPer100g: 25,
    carbsPer100g: 60,
    fatPer100g: 1.5,
    defaultPortionGrams: 180,
    defaultPortionUnit: 'bowl',
  },
  // Dal
  {
    name: 'Dal',
    aliases: ['dal', 'daal', 'lentils', 'dal tadka'],
    caloriesPer100g: 116,
    proteinPer100g: 9,
    carbsPer100g: 20,
    fatPer100g: 0.4,
    defaultPortionGrams: 180,
    defaultPortionUnit: 'bowl',
  },
  // Roti
  {
    name: 'Roti',
    aliases: ['roti', 'chapati', 'phulka', 'whole wheat bread'],
    caloriesPer100g: 297,
    proteinPer100g: 8,
    carbsPer100g: 49,
    fatPer100g: 7,
    defaultPortionGrams: 40,
    defaultPortionUnit: 'piece',
  },
  // Paneer
  {
    name: 'Paneer',
    aliases: ['paneer', 'cottage cheese', 'tofu'],
    caloriesPer100g: 265,
    proteinPer100g: 18,
    carbsPer100g: 1.2,
    fatPer100g: 21,
    defaultPortionGrams: 80,
    defaultPortionUnit: 'piece',
  },
  // Chicken Curry
  {
    name: 'Chicken Curry',
    aliases: ['chicken curry', 'chicken gravy', 'chicken sabzi'],
    caloriesPer100g: 165,
    proteinPer100g: 15,
    carbsPer100g: 5,
    fatPer100g: 9,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'bowl',
  },
  // Fish Curry
  {
    name: 'Fish Curry',
    aliases: ['fish curry', 'fish gravy', 'machher jhol', 'machli curry'],
    caloriesPer100g: 140,
    proteinPer100g: 16,
    carbsPer100g: 4,
    fatPer100g: 7,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'bowl',
  },
  // Biryani
  {
    name: 'Biryani',
    aliases: ['biryani', 'chicken biryani', 'veg biryani', 'mutton biryani'],
    caloriesPer100g: 185,
    proteinPer100g: 9,
    carbsPer100g: 24,
    fatPer100g: 6,
    defaultPortionGrams: 350,
    defaultPortionUnit: 'plate',
  },
  // Samosa
  {
    name: 'Samosa',
    aliases: ['samosa', 'samosas', 'sambusa'],
    caloriesPer100g: 260,
    proteinPer100g: 6,
    carbsPer100g: 32,
    fatPer100g: 13,
    defaultPortionGrams: 60,
    defaultPortionUnit: 'piece',
  },
  // Pakora
  {
    name: 'Pakora',
    aliases: ['pakora', 'pakoda', 'bhaji', 'fritters'],
    caloriesPer100g: 220,
    proteinPer100g: 5,
    carbsPer100g: 18,
    fatPer100g: 15,
    defaultPortionGrams: 60,
    defaultPortionUnit: 'piece',
  },
  // Luchi
  {
    name: 'Luchi',
    aliases: ['luchi', 'luchis', 'bengali puri'],
    caloriesPer100g: 320,
    proteinPer100g: 6,
    carbsPer100g: 42,
    fatPer100g: 15,
    defaultPortionGrams: 35,
    defaultPortionUnit: 'piece',
  },
  // Alur Dom
  {
    name: 'Alur Dom',
    aliases: ['alur dom', 'aloo dum', 'spicy potatoes'],
    caloriesPer100g: 120,
    proteinPer100g: 2,
    carbsPer100g: 18,
    fatPer100g: 5,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Kosha Mangsho
  {
    name: 'Kosha Mangsho',
    aliases: ['kosha mangsho', 'kasha mangsho', 'bengali mutton curry', 'mutton kosha'],
    caloriesPer100g: 220,
    proteinPer100g: 18,
    carbsPer100g: 5,
    fatPer100g: 14,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'bowl',
  },
  // Mishti Doi
  {
    name: 'Mishti Doi',
    aliases: ['mishti doi', 'misti doi', 'sweet yogurt', 'bengali sweet yogurt'],
    caloriesPer100g: 130,
    proteinPer100g: 4,
    carbsPer100g: 22,
    fatPer100g: 4,
    defaultPortionGrams: 100,
    defaultPortionUnit: 'serving',
  },
  // Fish Fry
  {
    name: 'Fish Fry',
    aliases: ['fish fry', 'fish finger', 'batter fried fish'],
    caloriesPer100g: 200,
    proteinPer100g: 18,
    carbsPer100g: 8,
    fatPer100g: 12,
    defaultPortionGrams: 100,
    defaultPortionUnit: 'piece',
  },
  // Macher Jhol
  {
    name: 'Macher Jhol',
    aliases: ['macher jhol', 'machher jhol', 'bengali fish curry', 'fish stew'],
    caloriesPer100g: 130,
    proteinPer100g: 15,
    carbsPer100g: 3,
    fatPer100g: 6,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'bowl',
  },
  // Basanti Pulao
  {
    name: 'Basanti Pulao',
    aliases: ['basanti pulao', 'bengali pulao', 'sweet pulao', 'mishit pulao'],
    caloriesPer100g: 190,
    proteinPer100g: 4,
    carbsPer100g: 32,
    fatPer100g: 5,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'plate',
  },
  // Chicken Kosha
  {
    name: 'Chicken Kosha',
    aliases: ['chicken kosha', 'bengali chicken curry', 'chicken kasha'],
    caloriesPer100g: 180,
    proteinPer100g: 16,
    carbsPer100g: 5,
    fatPer100g: 11,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'bowl',
  },
  // Egg
  {
    name: 'Egg',
    aliases: ['egg', 'eggs', 'anda', 'omelette', 'boiled egg'],
    caloriesPer100g: 155,
    proteinPer100g: 13,
    carbsPer100g: 1.1,
    fatPer100g: 11,
    defaultPortionGrams: 55,
    defaultPortionUnit: 'piece',
  },
  // Chicken
  {
    name: 'Chicken',
    aliases: ['chicken', 'chicken breast', 'chicken thigh', 'boneless chicken'],
    caloriesPer100g: 165,
    proteinPer100g: 31,
    carbsPer100g: 0,
    fatPer100g: 3.6,
    defaultPortionGrams: 100,
    defaultPortionUnit: 'piece',
  },
  // Fish
  {
    name: 'Fish',
    aliases: ['fish', 'fish fillet', 'rohu', 'katla', 'bhetki'],
    caloriesPer100g: 120,
    proteinPer100g: 22,
    carbsPer100g: 0,
    fatPer100g: 3,
    defaultPortionGrams: 100,
    defaultPortionUnit: 'piece',
  },
  // Mutton
  {
    name: 'Mutton',
    aliases: ['mutton', 'goat meat', 'lamb'],
    caloriesPer100g: 200,
    proteinPer100g: 20,
    carbsPer100g: 0,
    fatPer100g: 13,
    defaultPortionGrams: 100,
    defaultPortionUnit: 'piece',
  },
  // Bread
  {
    name: 'Bread',
    aliases: ['bread', 'white bread', 'brown bread', 'sandwich bread'],
    caloriesPer100g: 265,
    proteinPer100g: 9,
    carbsPer100g: 49,
    fatPer100g: 3.2,
    defaultPortionGrams: 30,
    defaultPortionUnit: 'slice',
  },
  // Burger
  {
    name: 'Burger',
    aliases: ['burger', 'hamburger', 'veggie burger'],
    caloriesPer100g: 250,
    proteinPer100g: 14,
    carbsPer100g: 25,
    fatPer100g: 11,
    defaultPortionGrams: 180,
    defaultPortionUnit: 'piece',
  },
  // Pizza
  {
    name: 'Pizza',
    aliases: ['pizza', 'pizza slice', 'margherita'],
    caloriesPer100g: 266,
    proteinPer100g: 11,
    carbsPer100g: 33,
    fatPer100g: 10,
    defaultPortionGrams: 100,
    defaultPortionUnit: 'slice',
  },
  // Pasta (raw / uncooked)
  {
    name: 'Pasta (raw)',
    aliases: ['raw pasta', 'uncooked pasta', 'dry pasta', 'raw spaghetti', 'raw macaroni', 'raw noodles'],
    caloriesPer100g: 370,
    proteinPer100g: 13,
    carbsPer100g: 75,
    fatPer100g: 1.5,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'bowl',
  },
  // Pasta
  {
    name: 'Pasta',
    aliases: ['pasta', 'spaghetti', 'macaroni', 'noodles'],
    caloriesPer100g: 131,
    proteinPer100g: 5,
    carbsPer100g: 25,
    fatPer100g: 1.1,
    defaultPortionGrams: 180,
    defaultPortionUnit: 'serving',
  },
  // Milk
  {
    name: 'Milk',
    aliases: ['milk', 'whole milk', 'toned milk', 'doodh'],
    caloriesPer100g: 58,
    proteinPer100g: 3,
    carbsPer100g: 4.8,
    fatPer100g: 3,
    defaultPortionGrams: 240,
    defaultPortionUnit: 'glass',
  },
  // Curd
  {
    name: 'Curd',
    aliases: ['curd', 'yogurt', 'dahi', 'yoghurt'],
    caloriesPer100g: 61,
    proteinPer100g: 3.5,
    carbsPer100g: 4.7,
    fatPer100g: 3.3,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Potato
  {
    name: 'Potato',
    aliases: ['potato', 'aloo', 'potatoes', 'alu'],
    caloriesPer100g: 77,
    proteinPer100g: 2,
    carbsPer100g: 17,
    fatPer100g: 0.1,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'piece',
  },
  // Coke
  {
    name: 'Coke',
    aliases: ['coke', 'coca cola', 'soda', 'soft drink'],
    caloriesPer100g: 42,
    proteinPer100g: 0,
    carbsPer100g: 10.6,
    fatPer100g: 0,
    defaultPortionGrams: 350,
    defaultPortionUnit: 'glass',
  },
  // Banana
  {
    name: 'Banana',
    aliases: ['banana', 'kela', 'bananas'],
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 23,
    fatPer100g: 0.3,
    defaultPortionGrams: 118,
    defaultPortionUnit: 'piece',
  },
  // Apple
  {
    name: 'Apple',
    aliases: ['apple', 'apples', 'seb'],
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 14,
    fatPer100g: 0.2,
    defaultPortionGrams: 182,
    defaultPortionUnit: 'piece',
  },
  // Butter
  {
    name: 'Butter',
    aliases: ['butter', 'makhan', 'white butter'],
    caloriesPer100g: 717,
    proteinPer100g: 0.9,
    carbsPer100g: 0.1,
    fatPer100g: 81,
    defaultPortionGrams: 14,
    defaultPortionUnit: 'tablespoon',
  },
  // Oil
  {
    name: 'Oil',
    aliases: ['oil', 'cooking oil', 'vegetable oil', 'mustard oil', 'sarson ka tel', 'refined oil'],
    caloriesPer100g: 884,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    defaultPortionGrams: 14,
    defaultPortionUnit: 'tablespoon',
  },
  // Salad
  {
    name: 'Salad',
    aliases: ['salad', 'salad bowl', 'green salad', 'kuchumber'],
    caloriesPer100g: 20,
    proteinPer100g: 1,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    defaultPortionGrams: 120,
    defaultPortionUnit: 'bowl',
  },
  // Mixed Vegetables
  {
    name: 'Mixed Vegetables',
    aliases: ['mixed vegetables', 'mixed veg', 'mishri sabji', 'mixed sabzi'],
    caloriesPer100g: 80,
    proteinPer100g: 2.5,
    carbsPer100g: 12,
    fatPer100g: 3.5,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Veg Pulao
  {
    name: 'Veg Pulao',
    aliases: ['veg pulao', 'vegetable pulao', 'veg pulav', 'mixed pulao'],
    caloriesPer100g: 150,
    proteinPer100g: 4,
    carbsPer100g: 27,
    fatPer100g: 3,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'plate',
  },
  // Paratha
  {
    name: 'Paratha',
    aliases: ['paratha', 'parantha', 'aloo paratha', 'stuffed paratha'],
    caloriesPer100g: 310,
    proteinPer100g: 7,
    carbsPer100g: 45,
    fatPer100g: 12,
    defaultPortionGrams: 40,
    defaultPortionUnit: 'piece',
  },
  // Naan
  {
    name: 'Naan',
    aliases: ['naan', 'naan bread', 'butter naan', 'garlic naan'],
    caloriesPer100g: 260,
    proteinPer100g: 8,
    carbsPer100g: 46,
    fatPer100g: 5,
    defaultPortionGrams: 50,
    defaultPortionUnit: 'piece',
  },
  // Chickpeas (raw / uncooked)
  {
    name: 'Chickpeas (raw)',
    aliases: ['raw chole', 'uncooked chole', 'raw chana', 'dry chana', 'raw chickpeas', 'uncooked chickpeas', 'dry chickpeas'],
    caloriesPer100g: 360,
    proteinPer100g: 19,
    carbsPer100g: 60,
    fatPer100g: 6,
    defaultPortionGrams: 180,
    defaultPortionUnit: 'bowl',
  },
  // Chole
  {
    name: 'Chole',
    aliases: ['chole', 'chana', 'chickpea curry', 'chana masala'],
    caloriesPer100g: 140,
    proteinPer100g: 7,
    carbsPer100g: 18,
    fatPer100g: 5,
    defaultPortionGrams: 180,
    defaultPortionUnit: 'bowl',
  },
  // Idli
  {
    name: 'Idli',
    aliases: ['idli', 'idly', 'idlis'],
    caloriesPer100g: 120,
    proteinPer100g: 3,
    carbsPer100g: 25,
    fatPer100g: 0.5,
    defaultPortionGrams: 40,
    defaultPortionUnit: 'piece',
  },
  // Dosa
  {
    name: 'Dosa',
    aliases: ['dosa', 'dosai', 'masala dosa', 'plain dosa', 'sada dosa'],
    caloriesPer100g: 130,
    proteinPer100g: 3,
    carbsPer100g: 24,
    fatPer100g: 2,
    defaultPortionGrams: 80,
    defaultPortionUnit: 'piece',
  },
  // Upma
  {
    name: 'Upma',
    aliases: ['upma', 'sooji upma', 'rava upma', 'uppumavu'],
    caloriesPer100g: 140,
    proteinPer100g: 3,
    carbsPer100g: 26,
    fatPer100g: 3,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Onion
  {
    name: 'Onion',
    aliases: ['onion', 'pyaaz', 'onions', 'kanda'],
    caloriesPer100g: 40,
    proteinPer100g: 1.1,
    carbsPer100g: 9,
    fatPer100g: 0.1,
    defaultPortionGrams: 70,
    defaultPortionUnit: 'piece',
  },
  // Aloo Gobi
  {
    name: 'Aloo Gobi',
    aliases: ['aloo gobi', 'aloo gobhi', 'potato cauliflower'],
    caloriesPer100g: 80,
    proteinPer100g: 2,
    carbsPer100g: 14,
    fatPer100g: 2.5,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Baingan Bharta
  {
    name: 'Baingan Bharta',
    aliases: ['baingan bharta', 'bharta'],
    caloriesPer100g: 85,
    proteinPer100g: 2,
    carbsPer100g: 10,
    fatPer100g: 4.5,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Bhindi Masala
  {
    name: 'Bhindi Masala',
    aliases: ['bhindi', 'okra', 'bhindi masala'],
    caloriesPer100g: 70,
    proteinPer100g: 2,
    carbsPer100g: 8,
    fatPer100g: 3.5,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Matar Paneer
  {
    name: 'Matar Paneer',
    aliases: ['matar paneer', 'mutter paneer', 'peas paneer'],
    caloriesPer100g: 210,
    proteinPer100g: 12,
    carbsPer100g: 10,
    fatPer100g: 14,
    defaultPortionGrams: 180,
    defaultPortionUnit: 'bowl',
  },
  // Dal Makhani
  {
    name: 'Dal Makhani',
    aliases: ['dal makhani', 'makhani dal'],
    caloriesPer100g: 160,
    proteinPer100g: 7,
    carbsPer100g: 18,
    fatPer100g: 8,
    defaultPortionGrams: 180,
    defaultPortionUnit: 'bowl',
  },
  // Pav Bhaji
  {
    name: 'Pav Bhaji',
    aliases: ['pav bhaji', 'bhaji pav'],
    caloriesPer100g: 150,
    proteinPer100g: 4,
    carbsPer100g: 22,
    fatPer100g: 5,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'plate',
  },
  // Kadhai Chicken
  {
    name: 'Kadhai Chicken',
    aliases: ['kadhai chicken', 'kadai chicken'],
    caloriesPer100g: 170,
    proteinPer100g: 18,
    carbsPer100g: 5,
    fatPer100g: 9,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'bowl',
  },
  // Chicken Tikka
  {
    name: 'Chicken Tikka',
    aliases: ['chicken tikka', 'tikka'],
    caloriesPer100g: 200,
    proteinPer100g: 25,
    carbsPer100g: 2,
    fatPer100g: 10,
    defaultPortionGrams: 100,
    defaultPortionUnit: 'piece',
  },
  // Oats (raw / dry)
  {
    name: 'Oats (raw)',
    aliases: ['raw oats', 'uncooked oats', 'dry oats', 'rolled oats', 'quick oats', 'raw oatmeal'],
    caloriesPer100g: 390,
    proteinPer100g: 17,
    carbsPer100g: 66,
    fatPer100g: 7,
    defaultPortionGrams: 80,
    defaultPortionUnit: 'bowl',
  },
  // Oats
  {
    name: 'Oats',
    aliases: ['oats', 'oatmeal', 'porridge'],
    caloriesPer100g: 67,
    proteinPer100g: 2.5,
    carbsPer100g: 12,
    fatPer100g: 1.4,
    defaultPortionGrams: 80,
    defaultPortionUnit: 'bowl',
  },
  // Cornflakes
  {
    name: 'Cornflakes',
    aliases: ['cornflakes', 'cereal'],
    caloriesPer100g: 100,
    proteinPer100g: 2,
    carbsPer100g: 22,
    fatPer100g: 0.5,
    defaultPortionGrams: 60,
    defaultPortionUnit: 'bowl',
  },
  // Tea
  {
    name: 'Tea',
    aliases: ['tea', 'chai', 'milk tea', 'green tea'],
    caloriesPer100g: 40,
    proteinPer100g: 1.5,
    carbsPer100g: 6,
    fatPer100g: 1.5,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'cup',
  },
  // Coffee
  {
    name: 'Coffee',
    aliases: ['coffee', 'filter coffee'],
    caloriesPer100g: 30,
    proteinPer100g: 1.2,
    carbsPer100g: 4,
    fatPer100g: 1,
    defaultPortionGrams: 200,
    defaultPortionUnit: 'cup',
  },
  // Juice
  {
    name: 'Juice',
    aliases: ['juice', 'fruit juice', 'orange juice'],
    caloriesPer100g: 45,
    proteinPer100g: 0.5,
    carbsPer100g: 11,
    fatPer100g: 0.1,
    defaultPortionGrams: 240,
    defaultPortionUnit: 'glass',
  },
  // Water
  {
    name: 'Water',
    aliases: ['water', 'mineral water'],
    caloriesPer100g: 0,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 0,
    defaultPortionGrams: 240,
    defaultPortionUnit: 'glass',
  },
  // Biscuits
  {
    name: 'Biscuits',
    aliases: ['biscuit', 'biscuits', 'cookie', 'cookies'],
    caloriesPer100g: 450,
    proteinPer100g: 6,
    carbsPer100g: 70,
    fatPer100g: 16,
    defaultPortionGrams: 15,
    defaultPortionUnit: 'piece',
  },
  // Cake
  {
    name: 'Cake',
    aliases: ['cake', 'pastry'],
    caloriesPer100g: 350,
    proteinPer100g: 4,
    carbsPer100g: 45,
    fatPer100g: 16,
    defaultPortionGrams: 80,
    defaultPortionUnit: 'slice',
  },
  // Ice Cream
  {
    name: 'Ice Cream',
    aliases: ['ice cream', 'kulfi'],
    caloriesPer100g: 200,
    proteinPer100g: 3,
    carbsPer100g: 24,
    fatPer100g: 11,
    defaultPortionGrams: 100,
    defaultPortionUnit: 'scoop',
  },
  // Honey
  {
    name: 'Honey',
    aliases: ['honey', 'shahad'],
    caloriesPer100g: 304,
    proteinPer100g: 0.3,
    carbsPer100g: 82,
    fatPer100g: 0,
    defaultPortionGrams: 21,
    defaultPortionUnit: 'tablespoon',
  },
  // Sugar
  {
    name: 'Sugar',
    aliases: ['sugar', 'cheeni', 'shakkar'],
    caloriesPer100g: 387,
    proteinPer100g: 0,
    carbsPer100g: 100,
    fatPer100g: 0,
    defaultPortionGrams: 12,
    defaultPortionUnit: 'tablespoon',
  },
  // Poha
  {
    name: 'Poha',
    aliases: ['poha', 'pohe', 'flattened rice'],
    caloriesPer100g: 130,
    proteinPer100g: 3,
    carbsPer100g: 27,
    fatPer100g: 1.5,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Chilla
  {
    name: 'Chilla',
    aliases: ['chilla', 'besan chilla', 'cheela'],
    caloriesPer100g: 150,
    proteinPer100g: 6,
    carbsPer100g: 15,
    fatPer100g: 8,
    defaultPortionGrams: 60,
    defaultPortionUnit: 'piece',
  },
  // Dhokla
  {
    name: 'Dhokla',
    aliases: ['dhokla', 'khaman'],
    caloriesPer100g: 115,
    proteinPer100g: 4,
    carbsPer100g: 20,
    fatPer100g: 2,
    defaultPortionGrams: 60,
    defaultPortionUnit: 'piece',
  },
  // Vada
  {
    name: 'Vada',
    aliases: ['vada', 'medu vada', 'wada'],
    caloriesPer100g: 200,
    proteinPer100g: 5,
    carbsPer100g: 22,
    fatPer100g: 10,
    defaultPortionGrams: 30,
    defaultPortionUnit: 'piece',
  },
  // Sambar
  {
    name: 'Sambar',
    aliases: ['sambar', 'sambhar'],
    caloriesPer100g: 50,
    proteinPer100g: 3,
    carbsPer100g: 8,
    fatPer100g: 1,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Rasam
  {
    name: 'Rasam',
    aliases: ['rasam', 'rasam soup'],
    caloriesPer100g: 25,
    proteinPer100g: 1,
    carbsPer100g: 4,
    fatPer100g: 0.5,
    defaultPortionGrams: 150,
    defaultPortionUnit: 'bowl',
  },
  // Papad
  {
    name: 'Papad',
    aliases: ['papad', 'papadum', 'poppadom'],
    caloriesPer100g: 380,
    proteinPer100g: 18,
    carbsPer100g: 55,
    fatPer100g: 8,
    defaultPortionGrams: 10,
    defaultPortionUnit: 'piece',
  },
  // Pickle
  {
    name: 'Pickle',
    aliases: ['pickle', 'achaar', 'aachar'],
    caloriesPer100g: 30,
    proteinPer100g: 0.5,
    carbsPer100g: 1,
    fatPer100g: 2,
    defaultPortionGrams: 15,
    defaultPortionUnit: 'serving',
  },
];
